# Tahap build aplikasi React
FROM node:18-alpine AS build

WORKDIR /app

# Salin file package.json dan install dependencies
COPY ./client/package*.json ./

RUN npm install

# Salin seluruh source code dan build aplikasi
COPY ./client ./
RUN npm run build

# Tahap serve file React menggunakan Nginx
FROM nginx:alpine

# Copy hasil build ke direktori default Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Ekspos port 80 untuk melayani file statis
EXPOSE 80

# Jalankan Nginx
CMD ["nginx", "-g", "daemon off;"]
