[project]
  name = "dramaku"

[env]
  DB_HOST = "db"
  DB_USER = "postgres"
  DB_PASSWORD = "dika1708"
  DB_NAME = "dramaku3"

[[services]]
  name = "db"
  dockerfile = "Dockerfile-db"
  ports = ["5432:5432"]
  env = { POSTGRES_USER = "postgres", POSTGRES_PASSWORD = "dika1708" }

[[services]]
  name = "python-seeder"
  dockerfile = "Dockerfile-python"
  env = { DB_HOST = "db", DB_USER = "postgres", DB_PASSWORD = "dika1708", DB_NAME = "dramaku3" }
  depends_on = ["db"]
  command = "python /app/seeder.py"
  healthcheck = { test = "python /app/seeder.py --check", interval = "30s", retries = 3, timeout = "30s" }

[[services]]
  name = "server"
  dockerfile = "Dockerfile-server"
  ports = ["8080:8080"]
  depends_on = ["python-seeder"]

[[services]]
  name = "client"
  dockerfile = "Dockerfile-client"
  ports = ["3000:3000"]
  depends_on = ["server"]

[[services]]
  name = "nginx"
  image = "nginx:latest"
  ports = ["80:80"]
  volumes = ["./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"]
  depends_on = ["client", "server"]
